#!/bin/bash

#These are variables you should looks at changing first:
TITLE="Well crap . . ."
LOADER_FOLDER="/boot/loader"
TARGET_FILE="$LOADER_FOLDER/entries/boot_snapshot.conf"
#First, let us define some variable to make my life easier
#############
#This is just to be safe and not assume path, and quality of life
grep=/usr/bin/grep
#Sets up an array to parse the default loader
defualt_loader_array=( $($grep default $LOADER_FOLDER/loader.conf) )
#Set the default loader
DEFAULT_LOADER="$LOADER_FOLDER/entries/${defualt_loader_array[1]}.conf"
#Array of latest boot snapshots
latestboot_array=( $(/usr/bin/snapper -c root list |
$grep boot |
/usr/bin/cut -b -5 |
/usr/bin/sort -nr))
# All just things snatched from the default loader
grab_from_loader() {
  $grep "$1" $DEFAULT_LOADER
}
OPTIONS=$(grab_from_loader options)
LINUX=$(grab_from_loader "linux ")
INITRD=$( (grab_from_loader initrd) )
# The only way I could figure out to make sure all the initrd options are
# Carried over. If you have any suggestions please, by all means, let me know
declare -a initrd_files
# This checks the INITRD array for all of the entries which are not the word "initrd" and
# adds them to the initrd_files array
for i in ${INITRD[@]}; do
  if [ "$i" != "initrd" ]; then
    initrd_files+=($i)
  fi
done
# This is to get the subvolume which the root is on
ROOT_SUBVOL_STNG=$(/usr/bin/btrfs sub get-default / )
ROOT_SUBVOL=${ROOT_SUBVOL_STNG##*path }
#### Done with viable declarations #####
#Now is the time to write to the file
#One carrot here to overwrite file
echo "title $TITLE (snapshot # ${latestboot_array[0]} )" > $TARGET_FILE
#The rest are 2 carrots to just cat onto the end of the file
echo $LINUX >> $TARGET_FILE
#Copies the initrd files one line at a time
for i in ${initrd_files[@]}; do
  echo "initrd "$i" " >> $TARGET_FILE
done
# Just adds the rootflag option at the end
echo "$OPTIONS rootflags=subvol=$ROOT_SUBVOL/.snapshots/${latestboot_array[0]}" >> $TARGET_FILE
